export const BOOKING_ADD_ITEM = 'BOOKING_ADD_ITEM'
export const BOOKING_REMOVE_ITEM = 'BOOKING_REMOVE_ITEM'

export const BOOKING_SAVE_SHIPPING_ADDRESS = 'BOOKING_SAVE_SHIPPING_ADDRESS'
export const BOOKING_CLEAR_ITEMS = 'BOOKING_CLEAR_ITEMS'




